version: '2'
services:
    wifi_mgmt-app:
        image: wifi_mgmt
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://wifi_mgmt-mysql:3306/wifi_mgmt?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=wifi_mgmt-elasticsearch:9300
        ports:
            - 8080:8080
    wifi_mgmt-mysql:
        extends:
            file: mysql.yml
            service: wifi_mgmt-mysql
    wifi_mgmt-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: wifi_mgmt-elasticsearch
