version: '2'
services:
    hub_cam-app:
        image: hub_cam
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://hub_cam-mysql:3306/hub_cam?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    hub_cam-mysql:
        extends:
            file: mysql.yml
            service: hub_cam-mysql
