version: '2'
services:
    demoangular1x-app:
        image: demoangular1x
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://demoangular1x-mysql:3306/demoangular1x?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    demoangular1x-mysql:
        extends:
            file: mysql.yml
            service: demoangular1x-mysql
